
using Common;

namespace MinecraftServerEngine
{
    public enum Block : int
    {
        Air,
        Stone,
        Granite,
        PolishedGranite,
        Diorite,
        PolishedDiorite,
        Andesite,
        PolishedAndesite,
        GrassBlock,
        Dirt,
        CoarseDirt,
        Podzol,
        Cobblestone,
        OakWoodPlanks,
        SpruceWoodPlanks,
        BirchWoodPlanks,
        JungleWoodPlanks,
        AcaciaWoodPlanks,
        DarkOakWoodPlanks,
        OakSapling,
        SpruceSapling,
        BirchSapling,
        JungleSapling,
        AcaciaSapling,
        DarkOakSapling,
        Bedrock,
        FlowingWater,
        StillWater,
        FlowingLava,
        StillLava,
        Sand,
        RedSand,
        Gravel,
        GoldOre,
        IronOre,
        CoalOre,
        OakWood,
        SpruceWood,
        BirchWood,
        JungleWood,
        OakLeaves,
        SpruceLeaves,
        BirchLeaves,
        JungleLeaves,
        Sponge,
        WetSponge,
        Glass,
        LapisLazuliOre,
        LapisLazuliBlock,
        Dispenser,
        Sandstone,
        ChiseledSandstone,
        SmoothSandstone,
        NoteBlock,



        EastBottomOakWoodStairs,
        WestBottomOakWoodStairs,
        SouthBottomOakWoodStairs,
        NorthBottomOakWoodStairs,
        EastTopOakWoodStairs,
        WestTopOakWoodStairs,
        SouthTopOakWoodStairs,
        NorthTopOakWoodStairs,
    }

}
