
namespace MinecraftServerEngine
{
    public enum Particle : int
    {
        Explode = 0,
        Largeexplode = 1,
        Hugeexplosion = 2,
        FireworksSpark = 3,
        Bubble = 4,
        Splash = 5,
        Wake = 6,
        Suspended = 7,
        Depthsuspend = 8,
        Crit = 9,
        MagicCrit = 10,
        Smoke = 11,
        Largesmoke = 12,
        Spell = 13,
        InstantSpell = 14,
        MobSpell = 15,
        MobSpellAmbient = 16,
        WitchMagic = 17,
        DripWater = 18,
        DripLava = 19,
        AngryVillager = 20,
        HappyVillager = 21,
        Townaura = 22,
        Note = 23,
        Portal = 24,
        Enchantmenttable = 25,
        Flame = 26,
        Lava = 27,
        Footstep = 28,
        Cloud = 29,
        Reddust = 30,
        Snowballpoof = 31,
        Snowshovel = 32,
        Slime = 33,
        Heart = 34,
        Barrier = 35,
        //Iconcrack_(id)_(data) = 36,
        //Blockcrack_(id+(data<<12)) = 37,
        //Blockdust_(id) = 38,
        Droplet = 39,
        Take = 40,
        Mobappearance = 41,
        Dragonbreath = 42,
        Endrod = 43,
        Damageindicator = 44,
        Sweepattack = 45,
        Fallingdust = 46,
        Totem = 47,
        Spit = 48,
    }
}
